### PR TITLE
- reference homepage

### LINKED ISSUE #9: Turn the reference sketches into a seeable format
Convert the sketch files into pngs/jpgs and have as reference for the devs.

### PR DESCRIPTION
**Pull request by pasinducw**
resolves #9

### CODE REVIEW

**Comment by nmasnadithya** [comment]
@pasinducw isn't it good to have the documents in another place, rather than adding them to the repo itself. Maybe in a separate repo ?
@vpj what are your thoughts on that ?

**Comment by pasinducw** [comment]
Yeah that crossed my mind, but at this level, do we need to goto such depths? 
Right now we just need the website to be up and running; so I think it's better to have less complications. Specially since we want to involve more people, when you have everything at one place, it will be a lot easier to manage.

**Comment by nmasnadithya** [comment]
> Yeah that crossed my mind, but at this level, do we need to goto such depths?
> Right now we just need the website to be up and running; so I think it's better to have less complications. Specially since we want to involve more people, when you have everything at one place, it will be a lot easier to manage.
> @nmasnadithya

The problem with that is, when someone clones the repo, just for a simple thing, they'll have a whole lot unwanted content downloaded

**Comment by nmasnadithya** [comment]
We can do something like, putting it in the repo [https://github.com/SLIOI/website.wiki.git](wiki)

**Comment by pasinducw** [comment]
oh, right sure then. Can you please go ahead and add the two files into a wiki?

**Comment by nmasnadithya** [comment]
> oh, right sure then. Can you please go ahead and add the two files into a wiki?

Done, check the wiki

**Pull request closed without merging**
